### ISSUE TITLE
`GXX` environment variable is undefined

### ISSUE THREAD

**Issue by maximilian-galanis** [StatisKit/AutoWIG#63]
I succeeded in installing AutoWIG on my machine (Ubuntu 16.04 with Miniconda3), but sadly I still got an error message as soon as I tried to parse an actual header. This was the error message:
>>> import autowig
>>> asg = autowig.AbstractSemanticGraph()
>>> asg = autowig.parser(asg, ['test.hpp'],['-x','c++','-std=c++11'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/galanis/miniconda3/envs/AutoWIG/lib/python3.7/site-packages/clanglite/autowig_parser.py", line 42, in autowig_parser
    header = pre_processing(asg, headers, flags, **kwargs)
  File "/home/galanis/miniconda3/envs/AutoWIG/lib/python3.7/site-packages/autowig/_parser.py", line 176, in pre_processing
    if "CONDA_PREFIX" in os.environ and not os.path.join(os.environ["CONDA_PREFIX"], os.environ['ROS_HOME'], 'sysroot', 'usr', 'include') in sysincludes:
  File "/home/galanis/miniconda3/envs/AutoWIG/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'GXX'

After I changed GXX with an existing variable, the parsing went fine and I could auto-generate wrappers.

**Comment by pfernique** [comment]
Thanks for the update.
Can you please show me the content of your **Conda** environment (this can be done using the `conda list` command in the environment containing **AutoWIG**) ?

**Comment by maximilian-galanis** [comment]
I just saw that I posted an incorrect error message. It should say:
```
import autowig
asg = autowig.AbstractSemanticGraph()
asg = autowig.parser(asg, ['test.hpp'],['-x','c++','-std=c++11'])
Traceback (most recent call last):
File "", line 1, in
File "/home/galanis/miniconda3/envs/AutoWIG/lib/python3.7/site-packages/clanglite/autowig_parser.py", line 42, in autowig_parser
header = pre_processing(asg, headers, flags, **kwargs)
File "/home/galanis/miniconda3/envs/AutoWIG/lib/python3.7/site-packages/autowig/_parser.py", line 176, in pre_processing
if "CONDA_PREFIX" in os.environ and not os.path.join(os.environ["CONDA_PREFIX"], os.environ['GXX'], 'sysroot', 'usr', 'include') in sysincludes:
File "/home/galanis/miniconda3/envs/AutoWIG/lib/python3.7/os.py", line 678, in getitem
raise KeyError(key) from None
KeyError: 'GXX'
```
so os.environ['GXX'] is causing the trouble. I then just exchanged GXX with the 'ROS_HOME' environment variable and it worked.


And here is my conda environment:
```
# packages in environment at /home/user-name/miniconda3/envs/AutoWIG:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
atk                       2.25.90           hb9dd440_1002    conda-forge
attrs                     19.1.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports.os              0.1.1                 py37_1000    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.1.23                     0  
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2019.3.9                 py37_0  
cffi                      1.12.2           py37hf0e25f4_1    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
clang                     4.0.1                       111    statiskit
coverage                  4.5.3            py37h14c3975_0    conda-forge
cryptography              2.5              py37hb7f436b_1    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
docutils                  0.14                  py37_1001    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
gdk-pixbuf                2.36.12           h49783d7_1002    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
gobject-introspection     1.58.2          py37h2da5eee_1000    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
gtk2                      2.24.31           hb68c50a_1001    conda-forge
harfbuzz                  2.3.1                h6824563_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        0.8                      py37_0    conda-forge
ipykernel                 5.1.0           py37h24bf2e0_1002    conda-forge
ipython                   7.4.0            py37h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.13.3                   py37_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1           py37h6bb024c_1002    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libclanglite              4.0.1                  py37_111    statiskit
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libstatiskit_core         0.1.0                       454    statiskit
libstatiskit_glm          0.1.0                       121    statiskit
libstatiskit_linalg       0.1.0                        61    statiskit
libstatiskit_stl          0.1.0                       209    statiskit
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
llvm                      4.0.1                       111    statiskit
mako                      1.0.7                    pypi_0    pypi
markupsafe                1.1.1            py37h14c3975_0    conda-forge
matplotlib                3.0.3                    py37_0    conda-forge
matplotlib-base           3.0.3            py37h167e16e_0    conda-forge
mistune                   0.8.4           py37h14c3975_1000    conda-forge
nbconvert                 5.4.1                      py_2    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nose                      1.3.7                 py37_1002    conda-forge
notebook                  5.7.8                    py37_0    conda-forge
numpy                     1.16.2           py37h7fc5cc3_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.5                ha44fe06_0    conda-forge
openssl                   1.0.2r               h7b6447c_0  
packaging                 19.0                       py_0    conda-forge
pandoc                    2.7.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14           h4ea9474_1004    conda-forge
parso                     0.3.4                      py_0    conda-forge
path.py                   11.5.0                     py_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.6.0                 py37_1000    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    5.4.1           py37h00a061d_1000    conda-forge
pip                       19.0.3                   py37_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                 py37_1000    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pypandoc                  1.4                      py37_1  
pyparsing                 2.3.1                      py_0    conda-forge
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pyrsistent                0.14.11          py37h14c3975_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
python                    3.7.1             hd21baee_1001    conda-forge
python-autowig            1.0.0                   py37_62    statiskit
python-clanglite          4.0.1                  py37_111    statiskit
python-dateutil           2.8.0                      py_0    conda-forge
python-parse              1.9.0                 py37_2748    statiskit
python-scons              3.0.0                 py37_2748    statiskit
python-statiskit          19.03.19              py37_1521    statiskit
python-statiskit_core     0.1.0                  py37_454    statiskit
python-statiskit_glm      0.1.0                  py37_121    statiskit
python-statiskit_linalg   0.1.0                   py37_61    statiskit
python-statiskit_stl      0.1.0                  py37_209    statiskit
python-toolchain          19.03.12               py37_110    statiskit
pytz                      2018.9                     py_0    conda-forge
pyyaml                    5.1              py37h14c3975_0    conda-forge
pyzmq                     18.0.1           py37h0e1adb2_0    conda-forge
qt                        5.6.2             hce4f676_1013    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py37_1000    conda-forge
scons-tools               19.03.12               py37_110    statiskit
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sphinx                    2.0.0                      py_2    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.1                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
tornado                   6.0.2            py37h516909a_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
widgetsnbextension        3.4.2                 py37_1000    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zipp                      0.3.3                      py_0    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

I also didn't find any information about which packages AutoWIG depends on and just installed a whole bunch of packages from Stasikit.

I also noticed that the current documentation is missing a lot of useful information (like code examples) that was present in older versions of the documentation. I there any reason why it was removed?

**Comment by pfernique** [comment]
Well, I just moved it to another repository https://github.com/StatisKit/FP17 in order to separate the **AutoWIG** code from the tutorial code of the article. And then forgot to update the **AutoWIG** documention.

Yet, some issues are now arising from the cohabitation of **Boost.Python** and **PyBind11** generators. Both are working fine but `SConscript` files of examples must be modified.
This is still work in progress but it's going slowly since I'm on other projects now.

Nevertheless. to install a working **AutoWIG**, could you try the following command:

```console
conda create -n autowig-toolchain autowig-toolchain -c statiskit -c defaults --override-channels
```

And launch the test in the corresponding environment ?

**Comment by maximilian-galanis** [comment]
Thank you! That's good to know!

I just installed a new environment with the provided command, but I still get the same error when trying to parse a header file.


Here you can find my current conda environment and the header I'm trying to parse with the following commands:
```
import autowig
asg = autowig.AbstractSemanticGraph()
asg = autowig.parser(asg,['features.h'],['-x','c++','-std=c++11'])
```

[features.txt](https://github.com/StatisKit/AutoWIG/files/3043319/features.txt) (I renamed it from .h to .txt so that I can upload it here)
[environment.txt](https://github.com/StatisKit/AutoWIG/files/3043313/environment.txt)

**Comment by pfernique** [comment]
Ok, `{{ compiler('c') }}` and  `{{ compiler('cxx') }}` were missing in the `autowig-toolchain` recipe.
Moreover, the content of the `GXX` variable has changed so I modified the **AutoWIG** source code accordingly.
I'm now generating new **Conda** packages.
Will let you now once done !

**Comment by pfernique** [comment]
Should work now...
Type the following commands

```console
conda env remove -n autowig-toolchain
conda create -n autowig-toolchain autowig-toolchain -c statiskit -c defaults --override-channels
```

and you will have the version `19.04.04` of `autowig-toolchain`, containing the `py37_63` build of `python-autowig`.

**Comment by maximilian-galanis** [comment]
Great, it works out of the box now!
Thank you for your help :)

**Comment by pfernique** [comment]
Thanks for your feedback !
Closing the issue now.
